/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';


import {
  SPHttpClient,
} from './model';


declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface MyComponent {
      'first': string;
      'last': string;
    }

    interface PnpSpfxHttptest {
      'httpClient': SPHttpClient;
      'httpClientConfiguration': any;
      'siteUrl': string;
    }
  }


    interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

    var HTMLMyComponentElement: {
      prototype: HTMLMyComponentElement;
      new (): HTMLMyComponentElement;
    };
    

    interface HTMLPnpSpfxHttptestElement extends StencilComponents.PnpSpfxHttptest, HTMLStencilElement {}

    var HTMLPnpSpfxHttptestElement: {
      prototype: HTMLPnpSpfxHttptestElement;
      new (): HTMLPnpSpfxHttptestElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'my-component': JSXElements.MyComponentAttributes;
    'pnp-spfx-httptest': JSXElements.PnpSpfxHttptestAttributes;
    }
  }

  namespace JSXElements {

    export interface MyComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }

    export interface PnpSpfxHttptestAttributes extends HTMLAttributes {
      'httpClient'?: SPHttpClient;
      'httpClientConfiguration'?: any;
      'siteUrl'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'pnp-spfx-httptest': HTMLPnpSpfxHttptestElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'pnp-spfx-httptest': HTMLPnpSpfxHttptestElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;