/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyComponent {

    }
  }

  interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface PnpSpfxWebparttitle {
      'className': string;
      'displayMode': DisplayMode;
      'onupdateproperty': string;
      'onupdatepropertyshort': string;
      'wpTitle': string;
    }
  }

  interface HTMLPnpSpfxWebparttitleElement extends StencilComponents.PnpSpfxWebparttitle, HTMLStencilElement {}

  var HTMLPnpSpfxWebparttitleElement: {
    prototype: HTMLPnpSpfxWebparttitleElement;
    new (): HTMLPnpSpfxWebparttitleElement;
  };
  interface HTMLElementTagNameMap {
    'pnp-spfx-webparttitle': HTMLPnpSpfxWebparttitleElement;
  }
  interface ElementTagNameMap {
    'pnp-spfx-webparttitle': HTMLPnpSpfxWebparttitleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'pnp-spfx-webparttitle': JSXElements.PnpSpfxWebparttitleAttributes;
    }
  }
  namespace JSXElements {
    export interface PnpSpfxWebparttitleAttributes extends HTMLAttributes {
      'className'?: string;
      'displayMode'?: DisplayMode;
      'onUpdateProperty'?: (event: CustomEvent<string>) => void;
      'onupdateproperty'?: string;
      'onupdatepropertyshort'?: string;
      'wpTitle'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;